### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by RedstoneWizard08** [TeamGalacticraft/DynWorlds#2]
Hi! I'm trying to use this for my own mod, and I can't figure out how to use it. Here's what I have so far (yes I am using Kotlin but it shouldn't cause any issues):

```kotlin
// Dimensions.kt
package dev.redacted.redacted.impl.init

import dev.galacticraft.dynamicdimensions.api.DynamicDimensionRegistry
import dev.redacted.redacted.impl.dim.MyDimension
import net.minecraft.server.MinecraftServer

object Dimensions {
    fun register(server: MinecraftServer) {
        val registry = server as DynamicDimensionRegistry

        MyDimension().create(registry)
    }
}

// Mod.kt
package dev.redacted.redacted.impl

object Mod {
    // ...
    fun init() {
        // ...
        LifecycleEvent.SERVER_STARTED.register(LifecycleEvent.ServerState { server: MinecraftServer ->
            RegistryLookup.init(server)
            Biomes.register()
            Dimensions.register(server)
        })
        // ...
    }
}
```

I am using Architectury and have imported the dependencies correctly in my `build.gradle.kts` files, and DynamicDimensions shows up.
Am I doing this right?

**Comment by marcus8448** [comment]
Based on your code, I can't tell what your use case for DynamicDimensions is. This library allows you to add or remove dimensions while the Minecraft server is running. If you're just trying to add a custom dimension, you can do so via datapacks (without using this mod).

**Comment by RedstoneWizard08** [comment]
@marcus8448 I know that. I'll share a few more code snippets in a few minutes. I want to be able to dynamically generate dimension configurations based on variables, so I do need this.

**Comment by RedstoneWizard08** [comment]
This is a private project, so I do have to remove a lot of details (including the package name lol). We don't want much of our plans being released until the mod is in a playable state, when we will open-source the mod. For now, here are a few cleaned snippets:

```kotlin
// src/main/kotlin/dev/redacted/redacted/impl/dim/CustomDimension.kt

package dev.redacted.redacted.impl.dim

import dev.galacticraft.dynamicdimensions.api.DynamicDimensionRegistry
import net.minecraft.resources.ResourceLocation
import net.minecraft.world.level.chunk.ChunkGenerator
import net.minecraft.world.level.dimension.DimensionType
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings

interface CustomDimension {
    fun getDimensionType(): DimensionType
    fun getChunkGenerator(): ChunkGenerator
    fun getGeneratorSettings(): NoiseGeneratorSettings
    fun getLocation(): ResourceLocation

    fun create(registry: DynamicDimensionRegistry) {
        registry.createDynamicDimension(getLocation(), getChunkGenerator(), getDimensionType());
    }
}
```

```kotlin
// src/main/kotlin/dev/redacted/redacted/impl/dim/ExampleDimension.kt

package dev.redacted.redacted.impl.dim

import dev.redacted.redacted.api.builder.DimensionTypeBuilder
import dev.redacted.redacted.api.builder.MonsterSettingsBuilder
import dev.redacted.redacted.impl.Redacted
import dev.redacted.redacted.impl.util.RegistryLookup
import dev.redacted.redacted.impl.init.Biomes
import net.minecraft.core.Holder
import net.minecraft.core.registries.Registries
import net.minecraft.resources.ResourceLocation
import net.minecraft.tags.TagKey
import net.minecraft.util.valueproviders.UniformInt
import net.minecraft.world.level.biome.FixedBiomeSource
import net.minecraft.world.level.block.Blocks
import net.minecraft.world.level.chunk.ChunkGenerator
import net.minecraft.world.level.dimension.DimensionType
import net.minecraft.world.level.levelgen.*

class ExampleDimension: CustomDimension {
    override fun getDimensionType(): DimensionType {
        return DimensionTypeBuilder()
                .ultraWarm(false)
                .natural(false)
                .respawnAnchorWorks(false)
                .bedWorks(false)
                .hasSkyLight(true)
                .hasCeiling(false)
                .coordinateScale(1.0)
                .ambientLight(4.0f)
                .logicalHeight(384)
                .effectsLocation(ResourceLocation("minecraft", "overworld"))
                .infiniburn(TagKey.create(Registries.BLOCK, ResourceLocation(Redacted.MOD_ID, "infiniburn_redacted")))
                .minY(-64)
                .height(384)
                .monsterSettings(MonsterSettingsBuilder()
                        .piglinSafe(true)
                        .hasRaids(false)
                        .blockLightLimit(0)
                        .lightTest(UniformInt.of(0, 4))
                        .build())
                .build()
    }

    override fun getChunkGenerator(): ChunkGenerator {
        return NoiseBasedChunkGenerator(
                FixedBiomeSource(Holder.Direct(Biomes.REDACTED_PLAINS!!)),
                Holder.direct(this.getGeneratorSettings())
        )
    }

    override fun getGeneratorSettings(): NoiseGeneratorSettings {
        return NoiseGeneratorSettings(
                NoiseSettings.create(-64, 384, 1, 2),
                Blocks.STONE.defaultBlockState(), // defaultBlock
                Blocks.AIR.defaultBlockState(), // defaultFluid
                NoiseRouter(
                        DensityFunctions.constant(0.0), // barrier
                        DensityFunctions.constant(0.0), // fluidLevelFloodedness
                        DensityFunctions.constant(0.0), // fluidLevelSpread
                        DensityFunctions.constant(0.0), // lava
                        DensityFunctions.constant(0.0), // temperature
                        DensityFunctions.constant(0.0), // vegetation
                        DensityFunctions.constant(0.0), // crontinents
                        DensityFunctions.constant(0.0), // erosion
                        DensityFunctions.constant(0.0), // depth
                        DensityFunctions.constant(0.0), // ridges
                        DensityFunctions.constant(0.0), // initialDensityWithoutJaggedness
                        DensityFunctions.interpolated(
                            RegistryLookup.DENSITY_FUNCTIONS?.get(
                                ResourceLocation("minecraft", "overworld/base_3d_noise")
                            )!!
                        ), // finalDensity
                        DensityFunctions.constant(0.0), // veinToggle
                        DensityFunctions.constant(0.0), // veinRidged
                        DensityFunctions.constant(0.0) // veinGap
                ),
                SurfaceRules.bandlands(), // surfaceRule
                mutableListOf(), // spawnTarget
                0, // seaLevel
                true, // disableMobGeneration
                false, // aquifersEnabled
                true, // oreVeinsEnabled
                false // legacyRandomSource
        )
    }

    override fun getLocation(): ResourceLocation {
        return ResourceLocation(Redacted.MOD_ID, "redacted")
    }
}
```

**Comment by marcus8448** [comment]
Thanks for the additional code samples. Is there a particular issue that you're running into? Your API usage looks correct.

**Comment by RedstoneWizard08** [comment]
The issue is that whenever I try to go into one of the dimensions, errors occur and the world doesn't generate. The error is also very vague.

**Comment by marcus8448** [comment]
Are you able to give me a stacktrace or tell me the error?

Also looking at your code again, I realize that you probably *want* to use `loadDynamicDimension` rather than `createDynamicDimension` so that the world isn't re-created every time the server starts.

**Comment by RedstoneWizard08** [comment]
Yeah, I'll re-run the client and check for a stack trace.

**Comment by RedstoneWizard08** [comment]
It just sits on "Loading Terrain."

**Comment by RedstoneWizard08** [comment]
Okay, there's no stack trace. This is what I can see.
![image](https://github.com/TeamGalacticraft/DynamicDimensions/assets/94275204/a226ef6f-02e4-4d84-9163-163b061a7727)

**Comment by RedstoneWizard08** [comment]
Changing it to `loadDynamicDimension` also does not help.

**Comment by marcus8448** [comment]
It looks like the server is failing to generate the world, which means your chunk generator is probably to blame.
The only part that DynamicDimensions manages is the creation of the level itself - the worldgen, ticking, etc is done by vanilla.

**Comment by marcus8448** [comment]
This is just a guess, but I think you should be using a reference here (you have an active server context).
```kotlin
FixedBiomeSource(Holder.Direct(Biomes.REDACTED_PLAINS!!)),
```

**Comment by RedstoneWizard08** [comment]
What do you mean by reference?

**Comment by marcus8448** [comment]
I mean in terms of the type of `Holder` that you pass to your biome source (currently you're using a direct holder rather than a registry reference holder).

**Comment by RedstoneWizard08** [comment]
okay, I'll try a reference holder

**Comment by RedstoneWizard08** [comment]
Yay!!! I have a stack trace now!!!

```log
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "objectSet" is null
	at net.minecraft.server.level.DistanceManager.removePlayer(DistanceManager.java:226) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.level.ChunkMap.move(ChunkMap.java:1120) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.level.ServerChunkCache.move(ServerChunkCache.java:473) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:999) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:16) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:22) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:764) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:743) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:675) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:46:16] [Server thread/ERROR] (Minecraft) Failed to handle packet net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos@6cf1ed60, suppressing error
 java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectSet.remove(Object)" because "objectSet" is null
	at net.minecraft.server.level.DistanceManager.removePlayer(DistanceManager.java:226) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.level.ChunkMap.move(ChunkMap.java:1120) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.level.ServerChunkCache.move(ServerChunkCache.java:473) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:999) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:42) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.network.protocol.PacketUtils.method_11072(PacketUtils.java:22) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:782) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:164) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:764) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:758) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:743) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:675) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[minecraft-merged-project-@fabric-1.20.1-loom.mappings.1_20_1.layered+hash.1900676243-v2.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by RedstoneWizard08** [comment]
This was solved, it was on my end with the way i handled inter-dimension teleporting. oops!

**Comment by sheazywi** [comment]
Good luck with ur project!
